from ._APDLCommands import APDL_Commands

ASTART = 0
class A(APDL_Commands):
    A = ASTART               # Defines an area by connecting keypoints.
    AADD = ASTART + 1        # Adds separate areas to create a single area.
    AATT = ASTART + 2        # Associates element attributes with the selected, unmeshed areas.
    ABEXTRACT = ASTART + 3   # Extracts the alpha-beta damping multipliers for Rayleigh damping.
    ABBRES = ASTART + 4      # Reads abbreviations from a coded file.
    ABBSAV = ASTART + 5      # Writes the current abbreviation set to a coded file.
    ABS = ASTART + 6         # Forms the absolute value of a variable.
    ACCAT = ASTART + 7       # Concatenates multiple areas in preparation for mapped meshing.
    ACCOPTION= ASTART + 8    # Specifies GPU accelerator capability options.
    ACEL = ASTART + 9        # Specifies the linear acceleration of the global Cartesian reference frame for the analysis.
    ACLEAR = ASTART + 10     # Deletes nodes and area elements associated with selected areas.
    ADAMS = ASTART + 11      # Performs solutions and writes flexible body information to a modal neutral file (Jobname.MNF) for use in an ADAMS analysis.
    ADD = ASTART + 12        # Adds (sums) variables.
    ADDAM = ASTART + 13      # Specifies the acceleration spectrum computation constants for the analysis of shock resistance of shipboard structures.
    ADELE = ASTART + 14      # Deletes unmeshed areas.
    ADGL = ASTART + 15       # Lists keypoints of an area that lie on a parametric degeneracy.
    ADRAG = ASTART + 16      # Generates areas by dragging a line pattern along a path.
    AEROCOEFF = ASTART + 17  # Computes the aero-damping and stiffness coefficients and writes them to an APDL array.
    AESIZE = ASTART + 18     # Specifies the element size to be meshed onto areas.
    AFILLT = ASTART + 19     # Generates a fillet at the intersection of two areas.
    AFLIST = ASTART + 20     # Lists the current data in the database.
    AFSURE = ASTART + 21     # Generates surface elements overlaid on the surface of existing solid elements and assigns the extra node as the closest fluid element node.
    AGEN = ASTART + 22       # Generates additional areas from a pattern of areas.
    AGLUE = ASTART + 23      # Generates new areas by "gluing" areas.
    AINA = ASTART + 24       # Finds the intersection of areas.
    AINP = ASTART + 25       # Finds the pairwise intersection of areas.
    AINV = ASTART + 26       # Finds the intersection of an area with a volume.
    AL = ASTART + 27         # Generates an area bounded by previously defined lines.
    ALIST = ASTART + 28      # Lists the defined areas.
    ALLSEL = ASTART + 29     # Selects all entities with a single command.
    ALPHAD = ASTART + 30     # Defines the mass matrix multiplier for damping.
    AMAP = ASTART + 31       # Generates a 2-D mapped mesh based on specified area corners.
    AMESH = ASTART + 32      # Generates nodes and area elements within areas.
    ANCNTR = ASTART + 33     # Produces an animated sequence of a contoured deformed shape.
    ANCUT = ASTART + 34      # Produces an animated sequence of Q-slices.
    ANCYC = ASTART + 35      # Applies a traveling wave animation to graphics data in a modal cyclic symmetry analysis.
    ANDATA = ASTART + 36     # Displays animated graphics data for nonlinear problems.
    ANDSCL = ASTART + 37     # Produces an animated sequence of a deformed shape.
    ANDYNA = ASTART + 38     # Produces an animated sequence of contour values through substeps.
    ANFLOW = ASTART + 39     # Produces an animated sequence of particle flow in a flowing fluid or a charged particle traveling in an electric or magnetic field.
    ANHARM = ASTART + 40     # Produces an animated sequence of time-harmonic results or complex mode shapes.
    ANIM = ASTART + 41       # Displays animated graphics data for linear problems.
    ANISOS = ASTART + 42     # Produces an animated sequence of an isosurface.
    ANMODE = ASTART + 43     # Produces an animated sequence of a mode shape.
    ANMRES = ASTART + 44     # Performs animation of results over multiple results files in an explicit dynamic structural analysis or fluid flow analysis with remeshing.
    ANORM = ASTART + 45      # Reorients area normals.
    ANPRES = ASTART + 46     # Produces an animated sequence of the time-harmonic pressure variation of an engine-order excitation in a cyclic harmonic analysis.
    ANSOL = ASTART + 47      # Specifies averaged nodal data to be stored from the results file in the solution coordinate system.
    ANSTOAQWA = ASTART + 48  # Creates an AQWA-LINE input file from the current Mechanical APDL model.
    ANSTOASAS = ASTART + 49  # Creates an ASAS input file from the current ANSYS model.
    ANTIME = ASTART + 50     # Generates a sequential contour animation over a range of time.
    ANTYPE = ASTART + 51     # Specifies the analysis type and restart status.
    AOFFST = ASTART + 52     # Generates an area, offset from a given area.
    AOVLAP = ASTART + 53     # Overlaps areas.
    APLOT = ASTART + 54      # Displays the selected areas.
    APORT = ASTART + 55      # Specifies input data for plane wave and acoustic duct ports.
    APPEND = ASTART + 56     # Reads data from the results file and appends it to the database.
    APTN = ASTART + 57       # Partitions areas.
    ARCLEN = ASTART + 58     # Activates the arc-length method.
    ARCTRM = ASTART + 59     # Controls termination of the solution when the arc-length method is used.
    AREAS = ASTART + 60      # Specifies "Areas" as the subsequent status topic.
    AREFINE = ASTART + 61    # Refines the mesh around specified areas.
    AREMESH = ASTART + 62    # Generates an area in which to create a new mesh for rezoning.
    AREVERSE = ASTART + 63   # Reverses the normal of an area, regardless of its connectivity or mesh status.
    AROTAT = ASTART + 64     # Generates cylindrical areas by rotating a line pattern about an axis.
    ARSCALE = ASTART + 65    # Generates a scaled set of areas from a pattern of areas.
    ARSYM = ASTART + 66      # Generates areas from an area pattern by symmetry reflection.
    ASBA = ASTART + 67       # Subtracts areas from areas.
    ASBL = ASTART + 68       # Subtracts lines from areas.
    ASBV = ASTART + 69       # Subtracts volumes from areas.
    ASBW = ASTART + 70       # Subtracts the intersection of the working plane from areas (divides areas).
    ASCRES = ASTART + 71     # Specifies the output type for an acoustic scattering analysis.
    ASEL = ASTART + 72       # Selects a subset of areas.
    ASIFILE = ASTART + 73    # Writes or reads one-way acoustic-structural coupling data.
    ASKIN = ASTART + 74      # Generates an area by "skinning" a surface through guiding lines.
    ASLL = ASTART + 75       # Selects those areas containing the selected lines.
    ASLV = ASTART + 76       # Selects those areas contained in the selected volumes.
    ASOL = ASTART + 77       # Specifies the acoustic solver with scattered field formulation.
    ASUB = ASTART + 78       # Generates an area using the shape of an existing area.
    ASUM = ASTART + 79       # Calculates and prints geometry statistics of the selected areas.
    ATAN = ASTART + 80       # Forms the arctangent of a complex variable.
    ATRAN = ASTART + 81      # Transfers a pattern of areas to another coordinate system.
    ATYPE = ASTART + 82      # Specifies "Analysis types" as the subsequent status topic.
    AUTOTS = ASTART + 83     # Specifies whether to use automatic time stepping or load stepping.
    AVPRIN = ASTART + 84     # Specifies how principal and vector sums are to be calculated.
    AVRES = ASTART + 85      # Specifies how results data will be averaged when PowerGraphics is enabled.
    AWAVE = ASTART + 86      # Specifies input data for an acoustic incident wave.
AEND = ASTART + len(A.__members__) - 1