from ._B import BEND
from ._APDLCommands import APDL_Commands

CSTART = BEND + 1

class C(APDL_Commands):
    CSTARSTARSTAR = CSTART # Places a comment in the output.
    CALC = CSTART + 1      # Specifies "Calculation settings" as the subsequent status topic.
    CAMPBELL = CSTART + 2  # Prepares the result file for a subsequent Campbell diagram of a prestressed structure.
    CBDOF = CSTART + 3     # Activates cut-boundary interpolation (for submodeling).
    CBMD = CSTART + 4      # Specifies preintegrated section mass matrix for composite-beam sections.
    CBMX = CSTART + 5      # Specifies preintegrated cross-section stiffness for composite beam sections.
    CBTE = CSTART + 6      # Specifies a thermal expansion coefficient for a composite beam section.
    CBTMP = CSTART + 7     # Specifies a temperature for composite-beam input.
    CDOPT = CSTART + 8     # Specifies format to be used for archiving geometry.
    CDREAD = CSTART + 9    # Reads a file of solid model and database information into the database.
    CDWRITE = CSTART + 10  # Writes geometry and load database items to a file.
    CE = CSTART + 11       # Defines a constraint equation relating degrees of freedom.
    CECHECK = CSTART + 12  # Check constraint equations and couplings for rigid body motions.
    CECMOD = CSTART + 13   # Modifies the constant term of a constraint equation during solution.
    CECYC = CSTART + 14    # Generates the constraint equations for a cyclic symmetry analysis
    CEDELE = CSTART + 15   # Deletes constraint equations.
    CEINTF = CSTART + 16   # Generates constraint equations at an interface.
    CELIST = CSTART + 17   # Lists the constraint equations.
    CENTER = CSTART + 18   # Defines a node at the center of curvature of 2 or 3 nodes.
    CEQN = CSTART + 19     # Specifies "Constraint equations" as the subsequent status topic.
    CERIG = CSTART + 20    # Defines a rigid region.
    CESGEN = CSTART + 21   # Generates a set of constraint equations from existing sets.
    CFACT = CSTART + 22    # Defines complex scaling factors to be used with operations.
    CGLOC = CSTART + 23    # Specifies the origin location of the acceleration coordinate system.
    CGOMGA = CSTART + 24   # Specifies the rotational velocity of the global origin.
    CGROW = CSTART + 25    # Defines crack-growth information.
    CHECK = CSTART + 26    # Checks current database items for completeness.
    CHKMSH = CSTART + 27   # Checks area and volume entities for previous meshes.
    CINT = CSTART + 28     # Defines parameters associated with fracture parameter calculations
    CIRCLE = CSTART + 29   # Generates circular arc lines.
    CISOL = CSTART + 30    # Stores fracture parameter information in a variable.
    CLOCAL = CSTART + 31   # Defines a local coordinate system relative to the active coordinate system.
    CLOG = CSTART + 32     # Forms the common log of a variable
    CLRMSHLN = CSTART + 33 # Clears meshed entities.
    CM = CSTART + 34       # Groups geometry items into a component.
    CMACEL = CSTART + 35   # Activates the element for use in a modal analysis.
    CMATRIX = CSTART + 36  # Performs electrostatic field solutions and calculates the self and mutual capacitances between multiple conductors.
    CMDELE = CSTART + 37   # Deletes a component or assembly definition.
    CMDOMEGA = CSTART + 38 # Specifies the rotational acceleration of an element component about a user-defined rotational axis.
    CMEDIT = CSTART + 39   # Edits an existing assembly.
    CMGRP = CSTART + 40    # Groups components and assemblies into an assembly.
    CMLIST = CSTART + 41   # Lists the contents of a component or assembly.
    CMMOD = CSTART + 42    # Modifies the specification of a component.
    CMOMEGA = CSTART + 43  # Specifies the rotational velocity of an element component about a user-defined rotational axis.
    CMPLOT = CSTART + 44   # Plots the entities contained in a component or assembly.
    CMROTATE = CSTART + 45 # Specifies the rotational velocity of an element component in a brake squeal analysis.
    CMSEL = CSTART + 46    # Selects a subset of components and assemblies.
    CMSFILE = CSTART + 47  # Specifies a list of component mode synthesis (CMS) results files for plotting results on the assembly.
    CMSOPT = CSTART + 48   # Specifies component mode synthesis (CMS) analysis options.
    CMWRITE = CSTART + 49  # Writes node and element components and assemblies to a file.
    CNCHECK = CSTART + 50  # Provides and/or adjusts the initial status of contact pairs.
    CNKMOD = CSTART + 51   # Modifies contact element key options.
    CNTR = CSTART + 52     # Redirects contact pair output quantities to a text file.
    CNVTOL = CSTART + 53   # Sets convergence values for nonlinear analyses.
    COMBINE = CSTART + 54  # Combines distributed memory parallel (Distributed ANSYS) files.
    COMPRESS = CSTART + 55 # Deletes all specified sets.
    CON4 = CSTART + 56     # Creates a conical volume anywhere on the working plane.
    CONE = CSTART + 57     # Creates a conical volume centered about the working plane origin.
    CONJUG = CSTART + 58   # Forms the complex conjugate of a variable.
    CORIOLIS = CSTART + 59 # Applies the Coriolis effect to a rotating structure.
    COUPLE = CSTART + 60   # Specifies "Node coupling" as the subsequent status topic.
    COVAL = CSTART + 61    # Defines PSD cospectral values.
    CP = CSTART + 62       # Defines (or modifies) a set of coupled degrees of freedom.
    CPCYC = CSTART + 63    # Couples the two side faces of a cyclically symmetric model for loadings that are the same on every segment.
    CPDELE = CSTART + 64   # Deletes coupled degree of freedom sets.
    CPINTF = CSTART + 65   # Defines coupled degrees of freedom at an interface.
    CPLGEN = CSTART + 66   # Generates sets of coupled nodes from an existing set.
    CPLIST = CSTART + 67   # Lists the coupled degree of freedom sets.
    CPMERGE = CSTART + 68  # Merges different couple sets with duplicate degrees of freedom into one couple set.
    CPNGEN = CSTART + 69   # Defines, modifies, or adds to a set of coupled degrees of freedom.
    CPSGEN = CSTART + 70   # Generates sets of coupled nodes from existing sets.
    CQC = CSTART + 71      # Specifies the complete quadratic mode combination method.
    CRPLIM = CSTART + 72   # Specifies the creep criterion for automatic time stepping.
    CS = CSTART + 73       # Defines a local coordinate system by three node locations.
    CSCIR = CSTART + 74    # Locates the singularity for non-Cartesian local coordinate systems.
    CSDELE = CSTART + 75   # Deletes a local coordinate system.
    CSKP = CSTART + 76     # Defines a local coordinate system by three keypoint locations.
    CSLIST = CSTART + 77   # Lists coordinate systems.
    CSWPLA = CSTART + 78   # Defines a local coordinate system at the origin of the working plane.
    CSYS = CSTART + 79     # Activates a previously defined coordinate system.
    CURR2D = CSTART + 80   # Calculates current flow in a 2-D conductor.
    CUTCONTROL = CSTART + 81 # Controls time-step cutback during a nonlinear solution.
    CVAR = CSTART + 82     # Computes covariance between two quantities.
    CYCCALC = CSTART + 83  # Calculates results from a cyclic harmonic mode-superposition analysis using the specifications defined by CYCSPEC.
    CYCFILES = CSTART + 84 # Specifies the data files where results are to be found for a cyclic symmetry mode-superposition harmonic analysis.
    CYCFREQ = CSTART + 85  # Specifies solution options for a cyclic symmetry mode-superposition harmonic analysis.
    CYCLIC = CSTART + 86   # Specifies a cyclic symmetry analysis.
    CYCOPT = CSTART + 87   # Specifies solution options for a cyclic symmetry analysis.
    CYCPHASE = CSTART + 88 # Provides tools for determining minimum and maximum possible result values from frequency couplets produced in a modal cyclic symmetry analysis.
    CYCSPEC = CSTART + 89  # Defines the set of result items for a subsequent CYCCALC command in postprocessing a cyclic harmonic mode-superposition analysis.
    CYL4 = CSTART + 90     # Creates a circular area or cylindrical volume anywhere on the working plane.
    CYL5 = CSTART + 91     # Creates a circular area or cylindrical volume by end points.
    CYLIND = CSTART + 92   # Creates a cylindrical volume centered about the working plane origin.
    CZDEL = CSTART + 93    # Edits or clears cohesive zone sections.
    CZMESH = CSTART + 94   # Create and mesh an interface area composed of cohesive zone elements.
CEND = CSTART + len(C.__members__) - 1