from ._D import DEND
from ._APDLCommands import APDL_Commands

ESTART = DEND + 1

class E(APDL_Commands):
    E = ESTART                  # Defines an element by node connectivity.
    EALIVE = ESTART + 1         # Reactivates an element (for the birth and death capability).
    ECPCHG = ESTART + 2         # Optimizes degree-of-freedom usage in a coupled acoustic model.
    EDADAPT = ESTART + 3        # Activates adaptive meshing in an explicit dynamic analysis.
    EDALE = ESTART + 4          # Assigns mesh smoothing to explicit dynamic elements that use the ALE formulation.
    EDASMP = ESTART + 5         # Creates a part assembly to be used in an explicit dynamic analysis.
    EDBOUND = ESTART + 6        # Defines a boundary plane for sliding or cyclic symmetry.
    EDBX = ESTART + 7           # Creates a box shaped volume to be used in a contact definition for explicit dynamics.
    EDBVIS = ESTART + 8         # Specifies global bulk viscosity coefficients for an explicit dynamics analysis.
    EDCADAPT = ESTART + 9       # Specifies adaptive meshing controls for an explicit dynamic analysis.
    EDCGEN = ESTART + 10        # Specifies contact parameters for an explicit dynamics analysis.
    EDCLIST = ESTART + 11       # Lists contact entity specifications in an explicit dynamics analysis.
    EDCMORE = ESTART + 12       # Specifies additional contact parameters for a given contact definition in an explicit dynamic analysis.
    EDCNSTR = ESTART + 13       # Defines various types of constraints for an explicit dynamic analysis.
    EDCONTACT = ESTART + 14     # Specifies contact surface controls for an explicit dynamics analysis.
    EDCPU = ESTART + 15         # Specifies CPU time limit for an explicit dynamics analysis.
    EDCRB = ESTART + 16         # Constrains two rigid bodies to act as one in an explicit dynamics analysis.
    EDCSC = ESTART + 17         # Specifies whether to use subcycling in an explicit dynamics analysis.
    EDCTS = ESTART + 18         # Specifies mass scaling and scale factor of computed time step for an explicit dynamics analysis.
    EDCURVE = ESTART + 19       # Specifies data curves for an explicit dynamic analysis.
    EDDAMP = ESTART + 20        # Defines mass weighted (Alpha) or stiffness weighted (Beta) damping for an explicit dynamics model.
    EDDBL = ESTART + 21         # Selects a numerical precision type of the explicit dynamics analysis.
    EDDC = ESTART + 22          # Deletes or deactivates/reactivates contact surface specifications in an explicit dynamic analysis.
    EDDRELAX = ESTART + 23      # Activates initialization to a prescribed geometry or dynamic relaxation for the explicit analysis.
    EDDUMP = ESTART + 24        # Specifies output frequency for the explicit dynamic restart file (d3dump).
    EDELE = ESTART + 25         # Deletes selected elements from the model.
    EDENERGY = ESTART + 26      # Specifies energy dissipation controls for an explicit dynamics analysis.
    EDFPLOT = ESTART + 27       # Allows plotting of explicit dynamics forces and other load symbols.
    EDGCALE = ESTART + 28       # Defines global ALE controls for an explicit dynamic analysis.
    EDHGLS = ESTART + 29        # Specifies the hourglass coefficient for an explicit dynamics analysis.
    EDHIST = ESTART + 30        # Specifies time-history output for an explicit dynamic analysis.
    EDHTIME = ESTART + 31       # Specifies the time-history output interval for an explicit dynamics analysis.
    EDINT = ESTART + 32         # Specifies number of integration points for explicit shell and beam output.
    EDIPART = ESTART + 33       # Defines inertia for rigid parts in an explicit dynamics analysis.
    EDIS = ESTART + 34          # Specifies stress initialization in an explicit dynamic full restart analysis.
    EDLCS = ESTART + 35         # Defines a local coordinate system for use in explicit dynamics analysis.
    EDLOAD = ESTART + 36        # Specifies loads for an explicit dynamics analysis.
    EDMP = ESTART + 37          # Defines material properties for an explicit dynamics analysis.
    EDNB = ESTART + 38          # Defines a nonreflecting boundary in an explicit dynamic analysis.
    EDNDTSD = ESTART + 39       # Allows smoothing of noisy data for explicit dynamics analyses and provides a graphical representation of the data.
    EDNROT = ESTART + 40        # Applies a rotated coordinate nodal constraint in an explicit dynamics analysis.
    EDOPT = ESTART + 41         # Specifies the type of output for an explicit dynamics analysis.
    EDOUT = ESTART + 42         # Specifies time-history output (ASCII format) for an explicit dynamics analysis.
    EDPART = ESTART + 43        # Configures parts for an explicit dynamics analysis.
    EDPC = ESTART + 44          # Selects and plots explicit dynamic contact entities.
    EDPL = ESTART + 45          # Plots a time dependent load curve in an explicit dynamic analysis.
    EDPVEL = ESTART + 46        # Applies initial velocities to parts or part assemblies in an explicit dynamic analysis.
    EDRC = ESTART + 47          # Specifies rigid/deformable switch controls in an explicit dynamic analysis.
    EDRD = ESTART + 48          # Switches a part from deformable to rigid or from rigid to deformable in an explicit dynamic analysis.
    EDREAD = ESTART + 49        # Reads explicit dynamics output into variables for time-history postprocessing.
    EDRI = ESTART + 50          # Defines inertia properties for a new rigid body that is created when a deformable part is switched to rigid in an explicit dynamic analysis.
    EDRST = ESTART + 51         # Specifies the output interval for an explicit dynamic analysis.
    EDRUN = ESTART + 52         # Specify LS-DYNA serial or parallel processing.
    EDSHELL = ESTART + 53       # Specifies shell computation controls for an explicit dynamics analysis.
    EDSOLV = ESTART + 54        # Specifies "explicit dynamics solution" as the subsequent status topic.
    EDSP = ESTART + 55          # Specifies small penetration checking for contact entities in an explicit dynamic analysis.
    EDSTART = ESTART + 56       # Specifies status (new or restart) of an explicit dynamics analysis.
    EDTERM = ESTART + 57        # Specifies termination criteria for an explicit dynamic analysis.
    EDTP = ESTART + 58          # Plots explicit elements based on their time step size.
    EDVEL = ESTART + 59         # Applies initial velocities to nodes or node components in an explicit dynamic analysis.
    EDWELD = ESTART + 60        # Defines a massless spotweld or generalized weld for use in an explicit dynamic analysis.
    EDWRITE = ESTART + 61       # Writes explicit dynamics input to an LS-DYNA input file.
    EEXTRUDE = ESTART + 62      # Extrudes 2-D plane elements into 3-D solids during a 2-D to 3-D analysis.
    EGEN = ESTART + 63          # Generates elements from an existing pattern.
    EINFIN = ESTART + 64        # Generates structural infinite elements from selected nodes.
    EINTF = ESTART + 65         # Defines two-node elements between coincident or offset nodes.
    EKILL = ESTART + 66         # Deactivates an element (for the birth and death capability).
    ELBOW = ESTART + 67         # Specifies degrees of freedom to be coupled for end release and applies section constraints to elbow elements.
    ELEM = ESTART + 68          # Specifies "Elements" as the subsequent status topic.
    ELIST = ESTART + 69         # Lists the elements and their attributes.
    EMAGERR = ESTART + 70       # Calculates the relative error in an electrostatic or electromagnetic field analysis.
    EMATWRITE = ESTART + 71     # Forces the writing of all the element matrices to File.EMAT.
    EMF = ESTART + 72           # Calculates the electromotive force (emf), or voltage drop along a predefined path.
    EMFT = ESTART + 73          # Summarizes electromagnetic forces and torques.
    EMID = ESTART + 74          # Adds or removes midside nodes.
    EMIS = ESTART + 75          # Specifies emissivity as a material property for the Radiation Matrix method.
    EMODIF = ESTART + 76        # Modifies a previously defined element.
    EMORE = ESTART + 77         # Adds more nodes to the just-defined element.
    EMSYM = ESTART + 78         # Specifies circular symmetry for electromagnetic sources.
    EMTGEN = ESTART + 79        # Generates a set of TRANS126 elements.
    EMUNIT = ESTART + 80        # Specifies the system of units for magnetic field problems.
    EN = ESTART + 81            # Defines an element by its number and node connectivity.
    ENDRELEASE = ESTART + 82    # Specifies degrees of freedom to be decoupled for end release.
    ENERSOL = ESTART + 83       # Specifies the total energies to be stored.
    ENGEN = ESTART + 84         # Generates elements from an existing pattern.
    ENORM = ESTART + 85         # Reorients shell element normals or line element node connectivity.
    ENSYM = ESTART + 86         # Generates elements by symmetry reflection.
    EORIENT = ESTART + 87       # Reorients solid element normals.
    EPLOT = ESTART + 88         # Produces an element display.
    EQSLV = ESTART + 89         # Specifies the type of equation solver.
    ERASE = ESTART + 90         # Explicitly erases the current display.
    EREAD = ESTART + 91         # Reads elements from a file.
    EREFINE = ESTART + 92       # Refines the mesh around specified elements.
    EREINF = ESTART + 93        # Generates reinforcing elements from selected existing (base) elements.
    ERESX = ESTART + 94         # Specifies extrapolation of integration point results.
    ERNORM = ESTART + 95        # Controls error estimation calculations.
    ERRANG = ESTART + 96        # Specifies the element range to be read from a file.
    ESCHECK = ESTART + 97       # Perform element shape checking for a selected element set.
    ESEL = ESTART + 98          # Selects a subset of elements.
    ESIZE = ESTART + 99         # Specifies the default number of line divisions.
    ESLA = ESTART + 100         # Selects those elements associated with the selected areas.
    ESLL = ESTART + 101         # Selects those elements associated with the selected lines.
    ESLV = ESTART + 102         # Selects elements associated with the selected volumes.
    ESOL = ESTART + 103         # Specifies element data to be stored from the results file.
    ESORT = ESTART + 104        # Sorts the element table.
    ESSOLV = ESTART + 105       # Performs a coupled electrostatic-structural analysis.
    ESTIF = ESTART + 106        # Specifies the matrix multiplier for deactivated elements.
    ESURF = ESTART + 107        # Generates elements overlaid on the free faces of selected nodes.
    ESYM = ESTART + 108         # Generates elements from a pattern by a symmetry reflection.
    ESYS = ESTART + 109         # Specifies the element coordinate system for the subsequent element definition.
    ET = ESTART + 110           # Defines a local element type from the element library.
    ETABLE = ESTART + 111       # Fills a table of element values for further processing.
    ETCHG = ESTART + 112        # Changes the element type of selected elements.
    ETCONTROL = ESTART + 113    # Control the element technologies used in element formulation (for applicable elements).
    ETDELE = ESTART + 114       # Deletes selected element types from the model.
    ETLIST = ESTART + 115       # Lists currently defined element types.
    ETYPE = ESTART + 116        # Specifies "Element types" as the subsequent status topic.
    EUSORT = ESTART + 117       # Restores original order of the element table.
    EWRITE = ESTART + 118       # Writes elements to a file.
    EXBOPT = ESTART + 119       # pecifies .EXB file output options in a CMS generation pass.
    EXOPTION = ESTART + 120     # Specifies the EXPROFILE options for the Mechanical APDL to ANSYS CFX profile file transfer.
    EXP = ESTART + 121          # Forms the exponential of a variable.
    EXPAND = ESTART + 122       # Displays the results of a modal cyclic symmetry analysis.
    EXPASS = ESTART + 123       # Specifies an expansion pass of an analysis.
    EXPROFILE = ESTART + 124    # Exports Mechanical APDL interface data on selected nodes to an ANSYS CFX Profile file.
    EXPSOL = ESTART + 125       # Specifies the solution to be expanded for mode-superposition analyses or substructure analyses.
    EXTOPT = ESTART + 126       # Controls options relating to the generation of volume elements from area elements.
    EXTREM = ESTART + 127       # Lists the extreme values for variables.
    EXUNIT = ESTART + 128       # Specifies the interface data unit labels to be written to the profile file from Mechanical APDL to ANSYS CFX transfer.

EEND = ESTART + len(E.__members__) - 1